import Head from "next/head";
import { useRouter } from "next/router";

import { Button } from "../Atoms/Button";

export default function LandPage() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Smart Debt Manager</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-6 text-center">
        <h1 className="text-3xl font-bold tracking-tight text-gray-200 sm:text-5xl">
          Manage <span className="text-black">Your Debt</span> efficiently
        </h1>
        <div className="running-text mt-6 text-lg leading-8 text-gray-300">
          <p>Welcome to Smart Debt Management – Your Partner in Business Financial Success.</p>
        </div>
        <div className="mt-10 flex items-center justify-center gap-x-6">
          <Button
            className="rounded-md bg-black px-4 py-3 text-lg font-semibold text-white shadow-lg hover:bg-gray-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-900"
            onClick={() => router.push("/auth")}>
            Get Started
          </Button>
        </div>
      </div>

      <style jsx>{`
        .running-text p {
          overflow: hidden;
          white-space: nowrap;
          animation: running-text 10s linear infinite;
          display: inline-block;
          transform: translateX(100%);
        }

        @keyframes running-text {
          0% {
            transform: translateX(100%);
          }
          25% {
            transform: translateX(-20%) translateY(-15px);
          }
          50% {
            transform: translateX(-40%) translateY(0);
          }
          75% {
            transform: translateX(-60%) translateY(15px);
          }
          100% {
            transform: translateX(0);
          }
        }
      `}</style>
    </>
  );
}
